### ISSUE TITLE
NoMethodError: undefined method `[]' for #<Daily::BatchRoomCreateRequest:...>

### ISSUE THREAD

**Issue by dimanyc** [daily-co/daily-ruby#10]
Hi, 

I'm using daily api ruby gem to try to create rooms in batches with my DailyApi class:
```ruby
# frozen_string_literal: true

class DailyApi
  SQUAD_ROOM_PROPERTIES = Daily::RoomProperties.new(
    enable_prejoin_ui: true,
    start_video_off: false,
    start_audio_off: false,
    enable_screenshare: true,
    enable_breakout_rooms: false,
    enable_chat: false,
    enable_emoji_reactions: false,
    enable_people_ui: true,
    enable_video_processing_ui: true,
    enable_pip_ui: false,
    enable_hand_raising: true,
    enable_network_ui: false,
    max_participants: 200,
    owner_only_broadcast: false
  )

  def batch_create_rooms(names = [])
    api = Daily::BatchRoomsApi.new

    opts = Daily::BatchRoomCreateRequest.new(
      rooms: names.map do |name|
        Daily::BatchRoomCreateRequestRoomsInner.new(
          name: name,
          privacy: "public",
          properties: SQUAD_ROOM_PROPERTIES
        )
      end
    )

    api.batch_room_create(opts) 
  end
end
```

for some reason, my #batch_create_rooms method returns:

```NoMethodError: undefined method `[]' for #<Daily::BatchRoomCreateRequest:0x0000000109e5c7c0 @rooms=[#<Daily::BatchRoomCreateRequestRoomsInner:0x0000000109e5c9a0 @name="squad-18", @privacy="public", @properties=#<Daily::RoomProperties:0x0000000109126920 @max_participants=200, @enable_people_ui=true, @enable_pip_ui=false, @enable_emoji_reactions=false, @enable_hand_raising=true, @enable_prejoin_ui=true, @enable_network_ui=false, @enable_breakout_rooms=false, @enable_screenshare=true, @enable_video_processing_ui=true, @enable_chat=false, @enable_shared_chat_history=true, @start_video_off=false, @start_audio_off=false, @owner_only_broadcast=false, @enable_recording="<not set>", @eject_at_room_exp=false, @enable_advanced_chat=false, @enable_hidden_participants=false, @sfu_switchover=0.5, @enable_adaptive_simulcast=true, @enable_multiparty_adaptive_simulcast=false, @enforce_unique_user_ids=false, @lang="en", @geo="NULL", @rtmp_geo="The closest available region to the SFU region used by the meeting.", @disable_rtmp_geo_fallback=false, @enable_terse_logging=false, @enable_transcription_storage=false, @recordings_template="{domain_name}/{room_name}/{epoch_time}.">>]>```

when I try to run it with:

```ruby
DailyApi.new.batch_create_rooms(['squad-18'])
```

**Comment by jamsea** [comment]
Hi @dimanyc I'll take a look at this later this week and see what's wrong 👀

**Comment by jamsea** [comment]
Hi @dimanyc I managed to get to this sooner than I thought.  The code below is working for me. It looks like the trick was to set `batch_room_create_request` in `opts`. Let me know if this works on your end

```ruby
# Load the gem
require 'daily-ruby'

p 'Version: ' + Daily::VERSION

# Setup authorization
Daily.configure do |config|
  # Configure Bearer authorization: bearerAuth
  config.api_key['sec0'] = ENV['DAILY_API_KEY']
  config.api_key_prefix['sec0'] = 'Bearer'
  config.debugging = true
  # Configure faraday connection
  # config.configure_faraday_connection { |connection| 'YOUR CONNECTION CONFIG PROC' }
end


inner_rooms = (0..9).map do |i|
  Daily::BatchRoomCreateRequestRoomsInner.new(
    name: "batch-test-room-#{i}-#{Time.now.to_i}",
    privacy: 'public',
    properties: {
      exp: (Time.now + (3600 * 2)).to_i # Delete the room after two hours
    }
  )
end

opts = {
  batch_room_create_request: Daily::BatchRoomCreateRequest.new(
    rooms: inner_rooms
  )
}

batch_room_api_instance = Daily::BatchRoomsApi.new


begin
  # Create new rooms in bulk
  room = batch_room_api_instance.batch_room_create(opts)
  p room
rescue Daily::ApiError => e
  puts "Error when calling RoomApi->batch_room_create: #{e}"
end
```

**Comment by dimanyc** [comment]
thanks for looking into this!
