### ISSUE TITLE
Create Room Api PIN Number

### ISSUE THREAD

**Issue by taylorkrause** [daily-co/daily-ruby#5]
Is it possible to include the ability to create a PIN Number for the rooms api create room request? https://docs.daily.co/guides/products/dial-in-dial-out/dialin-pin#create-provision-the-room-for-dial-in-with-a-pin-code

**Comment by rajneeshksoni** [comment]
yes, it is possible to create room along with assigning dialin to the room 

```
curl --request POST \
  --url https://api.daily.co/v1/rooms/ \
  --header 'Authorization: Bearer $TOKEN' \
  --header 'Content-Type: application/json' \
  --data '{"name": "my-test-room" ,"properties":{"dialin": {"display_name": "Phone Caller", "wait_for_meeting_start": true}, {"exp":'expr $(date +%s) + 31449600'}}}'

```

**Comment by taylorkrause** [comment]
I mean can you add it the capability to the ruby library?

**Comment by jamsea** [comment]
Hi @taylorkrause I'll try adding this next week!

**Comment by taylorkrause** [comment]
Thanks!!! :D
